# Generated by Django 5.2.1 on 2025-06-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_users',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='app.roomuser'),
        ),
    ]
